### PR TITLE
Improve validation

### PR DESCRIPTION
**Pull request by alxberardi**

### CODE REVIEW

**Comment by alxberardi** [comment]
Travis is broken because of ruby versions, it's a Travis issue I'll have to fix

**Comment by akilmadan** [comment]
:+1:

**Comment by msmirnoff** [comment]
:+1:

**Comment by msmirnoff** [comment]
@AlessandroBerardi 
By 'Travis issue' as I see, there is no problem in the PR, so it can be merged?

**Comment by alxberardi** [comment]
Let's wait until I fix the issue @msmirnoff , I'll merge it next week, there is no hurry.

**Comment by mnoack** [comment]
Travis fixed, it seems Travis was drunk that day and is now sober and working.

**Pull request merged**
